spring:
  jpa:
    open-in-view: false
  application:
    name: bookmark-service
server:
  port: 9090
  error:
    include-stacktrace: never
logging:
  level:
    root: info
    org:
      springframework:
        security: debug
